[tool.poetry]
name = "server-srv"
version = "0.1.0"
description = "application to test websockets with python"
authors = ["ramón molina"]

[tool.poetry.dependencies]
python = "^3.11"
websockets = "^10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
