[tool.poetry]
name = "client-srv"
version = "0.1.0"
description = ""
authors = ["ramón molina"]


[tool.poetry.dependencies]
python = "^3.11"
websockets = "^10.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
